server {
  listen 80;
  listen [::]:80;
  # HTTP (useful when you run on a non-standard port like :8080)
  server_name urr034.dev.openconsultinguk.com;

  root /usr/share/nginx/html;
  index index.html;

  location / { try_files $uri $uri/ /index.html; }

  location ~* \.(?:css|js|mjs|map|jpg|jpeg|png|gif|svg|ico|webp|avif|woff2?)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name urr034.dev.openconsultinguk.com;

 
  ssl_certificate     /etc/letsencrypt/live/urr034.dev.openconsultinguk.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/urr034.dev.openconsultinguk.com/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / { try_files $uri $uri/ /index.html; }

  location ~* \.(?:css|js|mjs|map|jpg|jpeg|png|gif|svg|ico|webp|avif|woff2?)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}
